name: Test take version

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

    - run:
        sudo apt-get install jq
    - run: |
        echo $(cat package.json | echo `jq .version`) >> $GITHUB_ENV_VERSION
        echo $(cat package.json | echo `jq .name`) >> $GITHUB_ENV_NAME
        
    - name: Send email
      uses: dawidd6/action-send-mail@v3.6.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USERNAME}}
          password: ${{secrets.GMAIL_PASSWORD}}
          subject: Message from github actions.
          to: aleksandra.cingovska
          from: alek
          secure: true
