name: Publish npm api bindings
on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

    - run: npm install
    - run: npm run compile

    - run: |
        npm version --no-git-tag-version from-git
        echo "NPM_PUBLISH_TAG=latest" >> $GITHUB_ENV

    - run: npm publish --tag "${{ env.NPM_PUBLISH_TAG }}"


